/*
Copyright 2020 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	vminstancev1alpha1 "k8s.io/ingress-gce/pkg/apis/vminstance/v1alpha1"
	versioned "k8s.io/ingress-gce/pkg/experimental/vminstance/client/clientset/versioned"
	internalinterfaces "k8s.io/ingress-gce/pkg/experimental/vminstance/client/informers/externalversions/internalinterfaces"
	v1alpha1 "k8s.io/ingress-gce/pkg/experimental/vminstance/client/listers/vminstance/v1alpha1"
)

// VMInstanceInformer provides access to a shared informer and lister for
// VMInstances.
type VMInstanceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.VMInstanceLister
}

type vMInstanceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewVMInstanceInformer constructs a new informer for VMInstance type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVMInstanceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredVMInstanceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredVMInstanceInformer constructs a new informer for VMInstance type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVMInstanceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CloudV1alpha1().VMInstances(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CloudV1alpha1().VMInstances(namespace).Watch(context.TODO(), options)
			},
		},
		&vminstancev1alpha1.VMInstance{},
		resyncPeriod,
		indexers,
	)
}

func (f *vMInstanceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredVMInstanceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *vMInstanceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&vminstancev1alpha1.VMInstance{}, f.defaultInformer)
}

func (f *vMInstanceInformer) Lister() v1alpha1.VMInstanceLister {
	return v1alpha1.NewVMInstanceLister(f.Informer().GetIndexer())
}
