/*
Copyright 2020 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "k8s.io/ingress-gce/pkg/apis/vminstance/v1alpha1"
)

// FakeVMInstances implements VMInstanceInterface
type FakeVMInstances struct {
	Fake *FakeCloudV1alpha1
	ns   string
}

var vminstancesResource = schema.GroupVersionResource{Group: "cloud.google.com", Version: "v1alpha1", Resource: "vminstances"}

var vminstancesKind = schema.GroupVersionKind{Group: "cloud.google.com", Version: "v1alpha1", Kind: "VMInstance"}

// Get takes name of the vMInstance, and returns the corresponding vMInstance object, and an error if there is any.
func (c *FakeVMInstances) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VMInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(vminstancesResource, c.ns, name), &v1alpha1.VMInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VMInstance), err
}

// List takes label and field selectors, and returns the list of VMInstances that match those selectors.
func (c *FakeVMInstances) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VMInstanceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(vminstancesResource, vminstancesKind, c.ns, opts), &v1alpha1.VMInstanceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VMInstanceList{ListMeta: obj.(*v1alpha1.VMInstanceList).ListMeta}
	for _, item := range obj.(*v1alpha1.VMInstanceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested vMInstances.
func (c *FakeVMInstances) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(vminstancesResource, c.ns, opts))

}

// Create takes the representation of a vMInstance and creates it.  Returns the server's representation of the vMInstance, and an error, if there is any.
func (c *FakeVMInstances) Create(ctx context.Context, vMInstance *v1alpha1.VMInstance, opts v1.CreateOptions) (result *v1alpha1.VMInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(vminstancesResource, c.ns, vMInstance), &v1alpha1.VMInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VMInstance), err
}

// Update takes the representation of a vMInstance and updates it. Returns the server's representation of the vMInstance, and an error, if there is any.
func (c *FakeVMInstances) Update(ctx context.Context, vMInstance *v1alpha1.VMInstance, opts v1.UpdateOptions) (result *v1alpha1.VMInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(vminstancesResource, c.ns, vMInstance), &v1alpha1.VMInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VMInstance), err
}

// Delete takes name of the vMInstance and deletes it. Returns an error if one occurs.
func (c *FakeVMInstances) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(vminstancesResource, c.ns, name), &v1alpha1.VMInstance{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVMInstances) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(vminstancesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VMInstanceList{})
	return err
}

// Patch applies the patch and returns the patched vMInstance.
func (c *FakeVMInstances) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VMInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(vminstancesResource, c.ns, name, pt, data, subresources...), &v1alpha1.VMInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VMInstance), err
}
