/*
Copyright 2020 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "k8s.io/ingress-gce/pkg/apis/migconfig/v1alpha1"
)

// FakeMigConfigs implements MigConfigInterface
type FakeMigConfigs struct {
	Fake *FakeCloudV1alpha1
	ns   string
}

var migconfigsResource = schema.GroupVersionResource{Group: "cloud.google.com", Version: "v1alpha1", Resource: "migconfigs"}

var migconfigsKind = schema.GroupVersionKind{Group: "cloud.google.com", Version: "v1alpha1", Kind: "MigConfig"}

// Get takes name of the migConfig, and returns the corresponding migConfig object, and an error if there is any.
func (c *FakeMigConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MigConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(migconfigsResource, c.ns, name), &v1alpha1.MigConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MigConfig), err
}

// List takes label and field selectors, and returns the list of MigConfigs that match those selectors.
func (c *FakeMigConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MigConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(migconfigsResource, migconfigsKind, c.ns, opts), &v1alpha1.MigConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MigConfigList{ListMeta: obj.(*v1alpha1.MigConfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.MigConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested migConfigs.
func (c *FakeMigConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(migconfigsResource, c.ns, opts))

}

// Create takes the representation of a migConfig and creates it.  Returns the server's representation of the migConfig, and an error, if there is any.
func (c *FakeMigConfigs) Create(ctx context.Context, migConfig *v1alpha1.MigConfig, opts v1.CreateOptions) (result *v1alpha1.MigConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(migconfigsResource, c.ns, migConfig), &v1alpha1.MigConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MigConfig), err
}

// Update takes the representation of a migConfig and updates it. Returns the server's representation of the migConfig, and an error, if there is any.
func (c *FakeMigConfigs) Update(ctx context.Context, migConfig *v1alpha1.MigConfig, opts v1.UpdateOptions) (result *v1alpha1.MigConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(migconfigsResource, c.ns, migConfig), &v1alpha1.MigConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MigConfig), err
}

// Delete takes name of the migConfig and deletes it. Returns an error if one occurs.
func (c *FakeMigConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(migconfigsResource, c.ns, name), &v1alpha1.MigConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMigConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(migconfigsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MigConfigList{})
	return err
}

// Patch applies the patch and returns the patched migConfig.
func (c *FakeMigConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MigConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(migconfigsResource, c.ns, name, pt, data, subresources...), &v1alpha1.MigConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MigConfig), err
}
