/*
Copyright 2020 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "k8s.io/ingress-gce/pkg/apis/migconfig/v1alpha1"
	scheme "k8s.io/ingress-gce/pkg/experimental/migconfig/client/clientset/versioned/scheme"
)

// MigConfigsGetter has a method to return a MigConfigInterface.
// A group's client should implement this interface.
type MigConfigsGetter interface {
	MigConfigs(namespace string) MigConfigInterface
}

// MigConfigInterface has methods to work with MigConfig resources.
type MigConfigInterface interface {
	Create(ctx context.Context, migConfig *v1alpha1.MigConfig, opts v1.CreateOptions) (*v1alpha1.MigConfig, error)
	Update(ctx context.Context, migConfig *v1alpha1.MigConfig, opts v1.UpdateOptions) (*v1alpha1.MigConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.MigConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.MigConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MigConfig, err error)
	MigConfigExpansion
}

// migConfigs implements MigConfigInterface
type migConfigs struct {
	client rest.Interface
	ns     string
}

// newMigConfigs returns a MigConfigs
func newMigConfigs(c *CloudV1alpha1Client, namespace string) *migConfigs {
	return &migConfigs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the migConfig, and returns the corresponding migConfig object, and an error if there is any.
func (c *migConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MigConfig, err error) {
	result = &v1alpha1.MigConfig{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("migconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MigConfigs that match those selectors.
func (c *migConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MigConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.MigConfigList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("migconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested migConfigs.
func (c *migConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("migconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a migConfig and creates it.  Returns the server's representation of the migConfig, and an error, if there is any.
func (c *migConfigs) Create(ctx context.Context, migConfig *v1alpha1.MigConfig, opts v1.CreateOptions) (result *v1alpha1.MigConfig, err error) {
	result = &v1alpha1.MigConfig{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("migconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(migConfig).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a migConfig and updates it. Returns the server's representation of the migConfig, and an error, if there is any.
func (c *migConfigs) Update(ctx context.Context, migConfig *v1alpha1.MigConfig, opts v1.UpdateOptions) (result *v1alpha1.MigConfig, err error) {
	result = &v1alpha1.MigConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("migconfigs").
		Name(migConfig.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(migConfig).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the migConfig and deletes it. Returns an error if one occurs.
func (c *migConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("migconfigs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *migConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("migconfigs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched migConfig.
func (c *migConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MigConfig, err error) {
	result = &v1alpha1.MigConfig{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("migconfigs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
