/*
Copyright 2020 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "k8s.io/ingress-gce/pkg/apis/vminstance/v1alpha1"
	scheme "k8s.io/ingress-gce/pkg/experimental/vminstance/client/clientset/versioned/scheme"
)

// VMInstancesGetter has a method to return a VMInstanceInterface.
// A group's client should implement this interface.
type VMInstancesGetter interface {
	VMInstances(namespace string) VMInstanceInterface
}

// VMInstanceInterface has methods to work with VMInstance resources.
type VMInstanceInterface interface {
	Create(ctx context.Context, vMInstance *v1alpha1.VMInstance, opts v1.CreateOptions) (*v1alpha1.VMInstance, error)
	Update(ctx context.Context, vMInstance *v1alpha1.VMInstance, opts v1.UpdateOptions) (*v1alpha1.VMInstance, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.VMInstance, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.VMInstanceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VMInstance, err error)
	VMInstanceExpansion
}

// vMInstances implements VMInstanceInterface
type vMInstances struct {
	client rest.Interface
	ns     string
}

// newVMInstances returns a VMInstances
func newVMInstances(c *CloudV1alpha1Client, namespace string) *vMInstances {
	return &vMInstances{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the vMInstance, and returns the corresponding vMInstance object, and an error if there is any.
func (c *vMInstances) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VMInstance, err error) {
	result = &v1alpha1.VMInstance{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vminstances").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VMInstances that match those selectors.
func (c *vMInstances) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VMInstanceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.VMInstanceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vminstances").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested vMInstances.
func (c *vMInstances) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("vminstances").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a vMInstance and creates it.  Returns the server's representation of the vMInstance, and an error, if there is any.
func (c *vMInstances) Create(ctx context.Context, vMInstance *v1alpha1.VMInstance, opts v1.CreateOptions) (result *v1alpha1.VMInstance, err error) {
	result = &v1alpha1.VMInstance{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("vminstances").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vMInstance).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a vMInstance and updates it. Returns the server's representation of the vMInstance, and an error, if there is any.
func (c *vMInstances) Update(ctx context.Context, vMInstance *v1alpha1.VMInstance, opts v1.UpdateOptions) (result *v1alpha1.VMInstance, err error) {
	result = &v1alpha1.VMInstance{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vminstances").
		Name(vMInstance.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vMInstance).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the vMInstance and deletes it. Returns an error if one occurs.
func (c *vMInstances) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vminstances").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *vMInstances) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vminstances").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched vMInstance.
func (c *vMInstances) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VMInstance, err error) {
	result = &v1alpha1.VMInstance{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("vminstances").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
